# YTLite Configuration
voice: pl-PL-MarekNeural  # Polish male voice (natural sounding)
# Alternative voices:
# pl-PL-ZofiaNeural - Polish female
# en-US-AriaNeural - English female  
# en-US-GuyNeural - English male

resolution: [1280, 720]  # 720p for faster processing
fps: 30
font_size: 48
style: minimalist

# Auto-upload settings
auto_upload: false  # Set to true when you're ready
upload_privacy: unlisted  # public, private, or unlisted
upload_schedule: "09:00"  # Time to upload daily content

# Shorts settings
generate_shorts: true
shorts_duration: 60  # seconds

# Thumbnail settings
thumbnail:
  waveform:
    # Height of the waveform strip as a fraction of image height
    height_ratio: 0.20
    # Waveform color and transparency (hex + alpha 0-255)
    color: "#00ff88"
    alpha: 180
    # Background strip color
    bg_color: "#000000"
    bg_alpha: 120
    # Axes (ticks, grid) appearance
    show_axes: true
    axes_color: "#ffffff"
    axes_alpha: 80
    # Baseline style (when no audio or silence)
    baseline_color: "#ffffff"
    baseline_alpha: 160
    baseline_width: 2
    # Time ticks granularity (seconds) and number of level lines
    time_tick_seconds: 10
    level_tick_count: 4

# Theme colors (hex)
themes:
  tech:
    bg_color: "#1e1e2e"
    text_color: "#cdd6f4"
    accent: "#89b4fa"
  philosophy:
    bg_color: "#2e2e3e"
    text_color: "#f5f5f5"
    accent: "#ffd700"
  wetware:
    bg_gradient: ["#667eea", "#764ba2"]
    text_color: "#ffffff"
    accent: "#ff6b6b"
