services:
  tauri-dev:
    build:
      context: ./tauri-youtube-oauth
      dockerfile: Dockerfile
    volumes:
      - ./tauri-youtube-oauth:/app
      - /tmp/.X11-unix:/tmp/.X11-unix # Mount X11 socket for GUI apps
    environment:
      - DISPLAY=$DISPLAY # Forward display
    working_dir: /app
    profiles: ["tauri"]
    command: tail -f /dev/null

  ytlite-base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: ytlite:base
    container_name: ytlite-base-build
    profiles: ["build"]

  ytlite:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: ytlite:app
    container_name: ytlite-app
    volumes:
      - .:/app
      - ./output:/app/output
      - ./credentials:/app/credentials
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG:-0}
    depends_on:
      - ytlite-base
    profiles: ["app"]

  ytlite-dev:
    image: ytlite:app
    container_name: ytlite-dev
    volumes:
      - .:/app
      - ./output:/app/output
      - ./credentials:/app/credentials
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG:-1}
    command: ["make", "dev-watch"]
    depends_on:
      - ytlite-base
    profiles: ["dev"]

  nginx:
    image: nginx:alpine
    container_name: ytlite-preview
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./output:/usr/share/nginx/html/output
    ports:
      - "8080:80"
    profiles: ["preview", "dev"]

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: ytlite:app
    container_name: ytlite-scheduler
    volumes:
      - .:/app
      - ./output:/app/output
      - ./credentials:/app/credentials
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG:-0}
      - AUTO_UPLOAD=${AUTO_UPLOAD:-false}
    command: ["python3", "src/scheduler.py"]
    depends_on:
      - ytlite-base
    profiles: ["automation"]

  tts-service:
    image: ytlite:app
    container_name: ytlite-tts
    volumes:
      - .:/app
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG:-0}
    command: ["python3", "src/ytlite.py", "watch"]
    depends_on:
      - ytlite-base
    profiles: ["tts"]

  video-generator:
    image: ytlite:app
    container_name: ytlite-video
    volumes:
      - .:/app
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG:-0}
    command: ["make", "generate"]
    depends_on:
      - tts-service
    profiles: ["video"]

  uploader:
    image: ytlite:app
    container_name: ytlite-uploader
    volumes:
      - .:/app
      - ./output:/app/output
      - ./credentials:/app/credentials
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG:-0}
      - AUTO_UPLOAD=${AUTO_UPLOAD:-true}
    command: ["make", "upload"]
    depends_on:
      - video-generator
    profiles: ["upload"]

networks:
  ytlite-network:
    driver: bridge
