version: '3.8'

services:
  # Base service - rarely changes, cached
  ytlite-base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: ytlite:base
    container_name: ytlite-base-build

  # Main YTLite application service
  ytlite:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: ytlite:app
    container_name: ytlite-app
    depends_on:
      - ytlite-base
    volumes:
      - ./content:/app/content
      - ./output:/app/output
      - ./credentials:/app/credentials
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: ["make", "help"]
    networks:
      - ytlite-network

  # Development service with live reload
  ytlite-dev:
    build:
      context: .
      dockerfile: Dockerfile.app  
    image: ytlite:app
    container_name: ytlite-dev
    depends_on:
      - ytlite-base
    volumes:
      - ./src:/app/src
      - ./content:/app/content
      - ./output:/app/output
      - ./credentials:/app/credentials
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - DEBUG=1
    working_dir: /app
    command: ["make", "dev-watch"]
    networks:
      - ytlite-network

  # Nginx for preview
  nginx:
    image: nginx:alpine
    container_name: ytlite-preview
    ports:
      - "8080:80"
    volumes:
      - ./output:/usr/share/nginx/html/output:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ytlite
    networks:
      - ytlite-network

  # Scheduler service for automation
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: ytlite:app
    container_name: ytlite-scheduler
    depends_on:
      - ytlite-base
    volumes:
      - ./content:/app/content
      - ./output:/app/output
      - ./credentials:/app/credentials
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app 
    working_dir: /app
    command: ["python3", "src/scheduler.py"]
    networks:
      - ytlite-network

networks:
  ytlite-network:
    driver: bridge
